version: '3.8'

services:
  db:
    build: ./Backend/db
    image: sanyitorok/elo-db
    restart: always
    networks:
      elonet:
        ipv4_address: 172.22.0.2
    environment:
      MYSQL_DATABASE: 'eloRatingDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'Sanyi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sakkiraly11'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sakkiraly11'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33061:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  backend:
    depends_on: 
      - db
    links:
      - db
    image: sanyitorok/elo-backend
    build: ./Backend
    networks:
      elonet:
        ipv4_address: 172.22.0.3
    restart: unless-stopped
    ports:
      - 3333:3333
    stdin_open: true
    tty: true
  frontend:
    depends_on: 
      - backend
    links:
      - backend
    image: sanyitorok/elo-calculator
    build: ./Frontend/elo-calculator

    networks:
      elonet:
        ipv4_address: 172.22.0.4
    ports:
      - 4444:80

networks:
  elonet:
    driver: bridge
    ipam:
     config:
      - subnet: 172.22.0.0/16
        gateway: 172.22.0.1